apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels:
      app: nginx-server
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        image: quay.io/yubolin/nginx-server
        command: 
        - 'sh'
        - '-c'
        - '/home/auto-reload-nginx.sh'
        ports:
        - containerPort: 443
        - containerPort: 80
